[package]
name = "solang"
version = "0.1.2"
authors = ["Sean Young <sean@mess.org>"]
homepage = "https://github.com/hyperledger-labs/solang"
documentation = "https://solang.readthedocs.io/"
license = "Apache-2.0 OR MIT"
build = "build.rs"
description = "Solang Solidity Compiler"
keywords = [ "solidity", "compiler", "ewasm", "llvm", "substrate" ]

[build-dependencies]
lalrpop = "0.19"

[dependencies]
lalrpop-util = "0.19"
regex = "1"
num-bigint = "0.2"
num-traits = "0.2"
num-derive = "0.3"
parity-wasm = "0.41"
clap = "2.33"
lazy_static = "1.4"
hex = "0.4"
tiny-keccak = "2.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = { version = "1.0" }
inkwell = { version = "0.1.0-llvm8sample", features = ["target-webassembly", "llvm8-0"] }
blake2-rfc = "0.2.18"
phf = { version = "0.8", features = ["macros"] }
unicode-xid = "0.2.0"

[dev-dependencies]
parity-scale-codec-derive = "1.2"
parity-scale-codec = "1.3"
ethabi = "12.0"
ethereum-types = "0.9"
wasmi = "0.6"
rand = "0.7"
sha2 = "0.9"

[profile.release]
lto = true
