[package]
name = "solang"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
homepage = "https://github.com/hyperledger-labs/solang"
documentation = "https://solang.readthedocs.io/"
license = "Apache-2.0 OR MIT"
build = "build.rs"
description = "Solidity to WASM Smart Contract Compiler"
keywords = [ "solidity", "compiler", "ewasm",  "llvm", "smart-contract", "substrate" ]

[build-dependencies]
lalrpop = "0.17"

[dependencies]
lalrpop-util = "0.17"
regex = "1"
num-bigint = "0.2"
num-traits = "0.2.6"
num-derive = "0.3"
parity-wasm = "0.41"
clap = "2.32.0"
lazy_static = "1.2.0"
hex = "0.4"
unescape = "0.1.0"
tiny-keccak = "1.5"
serde_json = "1.0"
serde = "1.0"
serde_derive = { version = "1.0" }

[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
branch = "llvm8-0"
features = ["target-webassembly", "llvm8-0"]

[dev-dependencies]
parity-scale-codec-derive = "1.1.0"
parity-scale-codec = "1.1.0"
ethabi = "11.0.0"
ethereum-types = "0.8.0"
wasmi = "0.6"
rand = "0.7"

[profile.release]
lto = true
