[package]
name = "solang"
version = "0.1.7"
authors = ["Sean Young <sean@mess.org>"]
homepage = "https://github.com/hyperledger-labs/solang"
documentation = "https://solang.readthedocs.io/"
license = "Apache-2.0"
build = "build.rs"
description = "Solang Solidity Compiler"
keywords = [ "solidity", "compiler", "ewasm", "llvm", "substrate" ]
edition = "2018"

[build-dependencies]
lalrpop = "0.19"
cc = "1.0"

[dependencies]
lalrpop-util = "0.19"
regex = "1"
num-bigint = "0.3"
num-traits = "0.2"
num-derive = "0.3"
parity-wasm = "0.42"
clap = "2.33"
lazy_static = "1.4"
hex = "0.4"
tiny-keccak = { version = "2.0", features = ["keccak"] }
serde_json = "1.0"
serde = "1.0"
serde_derive = { version = "1.0" }
inkwell = { version = "0.1.0-beta.2", features = ["target-webassembly", "target-bpf", "llvm11-0"] }
blake2-rfc = "0.2.18"
phf = { version = "0.8", features = ["macros"] }
unicode-xid = "0.2.0"
handlebars = "3.4"
contract-metadata = "0.2.0"
semver = { version = "0.11.0", features = ["serde"] }
tempfile = "3.1"
libc = "0.2"
tower-lsp = "0.13"
lsp-types = "0.81"
tokio = { version = "0.2", features = ["rt-core", "io-std"] }
base58 = "0.1.0"
sha2 = "0.9"
ripemd160 = "0.9"
bitvec = "0.20"
funty = "=1.1.0"
itertools = "0.10"

[dev-dependencies]
parity-scale-codec-derive = "2.0.0"
parity-scale-codec = "2.0.0"
ethabi = "13.0"
ethereum-types = "0.10"
wasmi = "0.7"
rand = "0.8"
sha2 = "0.9"
solana_rbpf = "=0.2.0"
byteorder = "1.3"
assert_cmd = "1.0"
bincode = "1.3"

[profile.release]
lto = true
