on:
  push:
    tags:
    - 'v*'

name: Build Release Binaries

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-18.04
    container: hyperledgerlabs/solang:ci
    steps:
    - name: Checkout sources
      # Make sure "git describe --tags" works for solang --version
      # checkout@v2 requires git 2.18 or higher, which is not in our image
      uses: actions/checkout@v1
    - name: Rust stable
      run: rustup default stable
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/solang
        asset_name: solang-linux
        tag: ${{ github.ref }}

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        # Make sure "git describe --tags" works for solang --version
        fetch-depth: 0
    - name: Download LLVM
      run: curl -sS -o c:\llvm.zip https://solang.io/download/llvm10.0-win.zip
    - name: Extract LLVM
      run: unzip c:\llvm.zip -d c:/
    - name: Add LLVM to Path
      run: echo "c:\llvm10.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/solang.exe
        asset_name: solang.exe
        tag: ${{ github.ref }}

  mac:
    name: Mac
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        # Make sure "git describe --tags" works for solang --version
        fetch-depth: 0
    - name: Download LLVM
      run: curl -sS -o llvm10.0-mac.tar.gz https://solang.io/download/llvm10.0-mac.tar.gz
    - name: Extract LLVM
      run: tar zxf llvm10.0-mac.tar.gz
    - name: Add LLVM to Path
      run: echo "$(pwd)/llvm10.0/bin" >> $GITHUB_PATH
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/solang
        asset_name: solang-mac
        tag: ${{ github.ref }}
