on:
  push:
    tags:
    - 'v*'

name: Build Release Binaries

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    container: hyperledgerlabs/solang:ci
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Compile stdlib
      run: clang-8 --target=wasm32 -c -emit-llvm -O3 -ffreestanding -fno-builtin -Wall stdlib.c sha3.c substrate.c ripemd160.c
      working-directory: ./stdlib
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/solang
        asset_name: solang_linux
        tag: ${{ github.ref }}

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Add LLVM to Path
      run: echo "::add-path::c:\llvm80\bin"
    - name: Download LLVM
      run: curl -sS -o c:\llvm.zip https://solang.io/download/llvm80.zip
    - name: Extract LLVM
      # unzip exists but always exits with code 1
      run: powershell Expand-Archive c:\llvm.zip -DestinationPath c:\
    - name: Compile stdlib
      run: clang --target=wasm32 -c -emit-llvm -O3 -ffreestanding -fno-builtin -Wall stdlib.c sha3.c substrate.c ripemd160.c
      working-directory: ./stdlib
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/solang.exe
        asset_name: solang.exe
        tag: ${{ github.ref }}
