name: test
on: [push, pull_request]
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-18.04
    container: hyperledgerlabs/solang:ci
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust stable
        run: rustup default stable
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  linux:
    name: Linux
    runs-on: ubuntu-18.04
    container: hyperledgerlabs/solang:ci
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Rust stable
      run: rustup default stable
    - name: Compile stdlib
      run: make
      working-directory:  ./stdlib
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Download LLVM
      run: curl -sS -o c:\llvm.zip https://solang.io/download/llvm10.0.zip
    - name: Extract LLVM
      run: unzip c:\llvm.zip -d c:/
    - name: Add LLVM to Path
      run: echo "c:\llvm10.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Compile stdlib
      run: make
      working-directory: ./stdlib
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  docker:
    name: Docker
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build dockerfile
      run: docker build .
