name: test
on: [push, pull_request]
jobs:
  repolinter:
    name: Repolinter
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run repolinter
        run: npx repolinter --rulesetUrl https://raw.githubusercontent.com/hyperledger-labs/hyperledger-community-management-tools/master/repo_structure/repolint.json

  lints:
    name: Lints
    runs-on: ubuntu-18.04
    container: hyperledgerlabs/solang:ci
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust stable
        run: rustup default stable
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --tests --bins -- -D warnings

  linux:
    name: Linux
    runs-on: ubuntu-18.04
    container: hyperledgerlabs/solang:ci
    steps:
    - name: Checkout sources
      # Make sure "git describe --tags" works for solang --version
      # checkout@v2 requires git 2.18 or higher, which is not in our image
      uses: actions/checkout@v1
    - name: Rust stable
      run: rustup default stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@master
      with:
        name: solang-linux
        path: ./target/debug/solang

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        # Make sure "git describe --tags" works for solang --version
        fetch-depth: 0
    - name: Download LLVM
      run: curl -sS -o c:\llvm.zip https://solang.io/download/llvm10.0-win.zip
    - name: Extract LLVM
      run: unzip c:\llvm.zip -d c:/
    - name: Add LLVM to Path
      run: echo "c:\llvm10.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@master
      with:
        name: solang.exe
        path: ./target/debug/solang.exe

  mac:
    name: Mac
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        # Make sure "git describe --tags" works for solang --version
        fetch-depth: 0
    - name: Download LLVM
      run: curl -sS -o llvm10.0-mac.tar.gz https://solang.io/download/llvm10.0-mac.tar.gz
    - name: Extract LLVM
      run: tar zxf llvm10.0-mac.tar.gz
    - name: Add LLVM to Path
      run: echo "$(pwd)/llvm10.0/bin" >> $GITHUB_PATH
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@master
      with:
        name: solang-mac
        path: ./target/debug/solang

  docker:
    name: Docker
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        # Make sure "git describe --tags" works for solang --version
        fetch-depth: 0
    - run: docker build . -t hyperledgerlabs/solang:latest
    - name: Login to DockerHub
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_KEY }}
    - run: docker push hyperledgerlabs/solang:latest
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

  solana:
    name: Solana Integration test
    runs-on: ubuntu-18.04
    container: ubuntu:18.04
    needs: linux
    services:
      solana:
        image: solanalabs/solana:v1.5.0
        ports:
          - 8899
          - 8900
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/download-artifact@master
      with:
        name: solang-linux
        path: bin
    - run: chmod 755 ./bin/solang
    - run: echo "$(pwd)/bin" >> $GITHUB_PATH
    - run: npm install
      working-directory: ./integration/solana
    - name: Build Solang contract
      run: npm run build
      working-directory: ./integration/solana
    - name: Set github env
      run: echo "RPC_URL=http://solana:8899/" >> $GITHUB_ENV
    - name: Deploy and test contract
      run: npm run test
      working-directory: ./integration/solana

  burrow:
    name: Burrow Integration test
    runs-on: ubuntu-18.04
    container: ubuntu:18.04
    needs: linux
    services:
      burrow:
        image: hyperledger/burrow:0.31.1
        ports:
          - 10997
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/download-artifact@master
      with:
        name: solang-linux
        path: bin
    - run: chmod 755 ./bin/solang
    - run: echo "$(pwd)/bin" >> $GITHUB_PATH
    - run: npm install
      working-directory: ./integration/burrow
    - name: Build Solang contract
      run: npm run build
      working-directory: ./integration/burrow
    - name: Set github env
      run: echo "RPC_URL=burrow:10997" >> $GITHUB_ENV
    - name: Deploy and test contract
      run: npm run test
      working-directory: ./integration/burrow

  vscode:
    name: Visual Code Extension
    runs-on: ubuntu-18.04
    needs: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: solang-linux
        path: /home/runner/.config/Code/User/globalStorage/solang.solang/
    - run: chmod 755 $HOME/.config/Code/User/globalStorage/solang.solang/solang
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
      working-directory: ./vscode
    - run: npm run compile
      working-directory: ./vscode
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./vscode
        run: npm test
    - run: npm install -g vsce
      working-directory: ./vscode
    - run: vsce package
      working-directory: ./vscode
