name: test
on: [push, pull_request]
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-20.04
    container: hyperledgerlabs/solang:ci
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust stable
        run: rustup default stable
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  linux:
    name: Linux
    runs-on: ubuntu-20.04
    container: hyperledgerlabs/solang:ci
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Rust stable
      run: rustup default stable
    - name: Compile stdlib
      run: clang-10 --target=wasm32 -c -emit-llvm -O3 -ffreestanding -fno-builtin -Wall stdlib.c sha3.c substrate.c ripemd160.c
      working-directory:  ./stdlib
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Download LLVM
      run: curl -sS -o c:\llvm.zip https://solang.io/download/llvm10.0.zip
    - name: Extract LLVM
      run: unzip c:\llvm.zip -d c:/
    - name: Add LLVM to Path
      run: echo "::add-path::c:\llvm10.0\bin"
    - name: Compile stdlib
      run: clang --target=wasm32 -c -emit-llvm -O3 -ffreestanding -fno-builtin -Wall stdlib.c sha3.c substrate.c ripemd160.c
      working-directory: ./stdlib
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  docker:
    name: Docker
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build dockerfile
      run: docker build .
